##########################################
# Clash.Meta 完整配置模板
# 适用于 Linux / 路由器 / 斐讯 N1 / Windows
##########################################

# --------------------------
# 订阅节点
# --------------------------
proxy-providers:
  WSH:
    url: "http://wushuhao.wang:3003/wsh/download/collection/wsh" # 填入你的订阅地址
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: 直连

# --------------------------
# 静态节点
# --------------------------
proxies:
  - {name: 直连, type: direct}
  - {name: 拒绝, type: reject}

# --------------------------
# 全局配置
# --------------------------
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
# interface-name: enp6s18
log-level: warning
find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

# --------------------------
# 嗅探模块
# --------------------------
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
    - "+.youtube.com"
    - "+.googlevideo.com"
  skip-domain:
    - "+.baidu.com"
    - "+.qq.com"
    - "+.alipay.com"
    - "+.bank.com"

# --------------------------
# TUN 透明代理
# --------------------------
tun:
  enable: true
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  #device: nikki
  auto-route: false
  auto-redirect: false          # 建议开启 Linux / N1 全局透明代理
  auto-detect-interface: false  # 自动识别出口网卡

# --------------------------
# DNS 模块
# --------------------------
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:China_Domain,China_Domain"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time.*.com"
    - "+.market.xiaomi.com"
  default-nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29

# --------------------------
# 代理组
# --------------------------
proxy-groups:
  - {name: 节点选择, type: select, proxies: [自建香港, 香港故转, 台湾故转, 日本故转, 新加坡故转, 美国故转]}
  - {name: Google, type: select, proxies: [自建香港, 香港故转, 台湾故转, 日本故转, 新加坡故转, 美国故转]}
  - {name: Youtube, type: select, proxies: [自建香港, 香港故转, 台湾故转, 日本故转, 新加坡故转, 美国故转]}
  - {name: Netflix, type: select, proxies: [自建香港, 香港故转, 台湾故转, 日本故转, 新加坡故转, 美国故转]}
  - {name: OpenAI, type: select, proxies: [台湾故转, 日本故转, 新加坡故转, 美国故转, 自建香港, 香港故转]}
  - {name: Telegram, type: select, proxies: [自建香港, 香港故转, 台湾故转, 日本故转, 新加坡故转, 美国故转]}
  - {name: 自建香港, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)wushuhao"}
  - {name: 香港故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?i)港|hk|hongkong|hong kong"}
  - {name: 台湾故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?i)台|tw|taiwan|tai wan"}
  - {name: 日本故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?i)日|jp|japan"}
  - {name: 新加坡故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?i)新加坡|坡|狮城|SG|Singapore"}
  - {name: 美国故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?i)美|unitedstates|united states"}

# --------------------------
# 规则匹配
# --------------------------
rules:
  - RULE-SET,Lan,直连
  - RULE-SET,Advertising,拒绝
  - RULE-SET,Advertising_Domain,拒绝
  - RULE-SET,China,直连
  - RULE-SET,China_Domain,直连
  - RULE-SET,ChinaIPs_IP,直连
  - RULE-SET,Apple,直连
  - RULE-SET,Apple_Domain,直连
  - RULE-SET,AppleTV,直连
  - RULE-SET,Google,Google
  - RULE-SET,Youtube,Youtube
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Netflix_IP,Netflix
  - RULE-SET,Speedtest,直连
  - RULE-SET,OpenAI,OpenAI
  - RULE-SET,Telegram,Telegram
  - MATCH,节点选择

# --------------------------
# 规则锚点
# --------------------------
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: yaml}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: text}
  class: &class {type: http, interval: 86400, behavior: classical, format: yaml}

# --------------------------
# 规则提供者
# --------------------------
rule-providers:
  Lan: { <<: *class, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml"}
  Advertising: { <<: *class, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml"}
  Advertising_Domain: { <<: *domain, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.txt"}
  China: { <<: *class, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.yaml"}
  China_Domain: { <<: *domain, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple_Domain.txt"}
  ChinaIPs_IP: { <<: *ip, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs_IP.yaml"}
  Apple: { <<: *class, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml"}
  Apple_Domain: { <<: *domain, url: "https://gh.wsh1993.top/https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple_Domain.txt"}
  AppleTV: { <<: *class, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleTV/AppleTV.yaml"}
  Speedtest: { <<: *class, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml"}
  Google: { <<: *class, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml"}
  Youtube: { <<: *class, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"}
  Netflix: { <<: *class, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml"}
  Netflix_IP: { <<: *ip, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix_IP.yaml"}
  OpenAI: { <<: *class, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml"}
  Telegram: { <<: *class, url: "https://gh.wsh1993.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"}
